# Generated by Django 4.2.6 on 2023-10-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.CharField(max_length=500),
        ),
    ]
